### ISSUE TITLE
Review of january-website-with-jekyll

### ISSUE THREAD

**Issue by jonahgraham** [Jdarroy/Jdarroy.github.io#1]
- [x] "(find how to install here)." doesn't link to anything.
- [x] "They got html balise" -- not sure what that means
- [ ] under "So when Jekyll do the generation he put each file with this structure." that screenshot is of which file? Is that defaults.html?
for the screenshots of files, can you do two things: 
- [x] a) change to formatted/highlighted source code that can be copy/pasted 
- [x] b) link to the file in github
- [x] " inside theese two" typo in these
- nice demo of how loops connect to output, really helps readability

**Comment by Jdarroy** [comment]
done

**Comment by jonahgraham** [comment]
All looks good. Just one thing that needs improvement for me, the code examples are now blocks of code, but they are not source formatted. As a lot of the code samples we want to post are Java, can you please investigate and put in an example of a Java formatted (coloured) code block.

**Comment by Jdarroy** [comment]
I find something for the coloration, tell me if you like it

**Comment by jonahgraham** [comment]
That looks great.
